#!/bin/bash
# Appends a line to /etc/privoxy/config to enable network access
enp0s8="ip address show enp0s8 | grep 'inet ' | sed -e 's/^.*inet //' -e 's/\/.*$//'"
mipp=$(eval $enp0s8)
mip=`echo $mipp | tr -cd "[:print:]\n"`
port=8118
#
echo "listen-address ${mip}:${port} # inserted by listen-address-enp0s8" >>/etc/privoxy/config
